export { default as conditional } from '@/primitives/conditional'
export { default as foundation } from '@/primitives/foundation'
export { default as variant } from '@/primitives/variant'

export * from '@/foundations/color'
export * from '@/foundations/display'
export * from '@/foundations/flex'
export * from '@/foundations/layout'
export * from '@/foundations/margin'
export * from '@/foundations/padding'
export * from '@/foundations/position'
export * from '@/foundations/text-align'
